
import type { Vehicle } from './types';

export const vehicles: Vehicle[] = [
  // 4-Wheelers
  {
    id: '1',
    make: 'Maruti Suzuki',
    model: 'Swift',
    year: 2021,
    price: 650000,
    kmsDriven: 25000,
    fuelType: 'Petrol',
    condition: 'Like New',
    imageUrl: 'https://picsum.photos/seed/swift/600/400',
    imageHint: 'red hatchback',
    verified: true,
    transmission: 'Manual',
    engine: '1.2L',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'Hatchback',
    registration: 'MH-12',
    insurance: 'Comprehensive',
    color: 'Red',
    mileage: '23.2 kmpl',
    seatingCapacity: 5,
    vehicleType: '4-wheeler',
    detailImages: {
      Exterior: ['https://picsum.photos/seed/swift-ext1/800/600', 'https://picsum.photos/seed/swift-ext2/800/600', 'https://picsum.photos/seed/swift-ext3/800/600'],
      Interior: ['https://picsum.photos/seed/swift-int1/800/600', 'https://picsum.photos/seed/swift-int2/800/600'],
      Engine: ['https://picsum.photos/seed/swift-eng1/800/600'],
      Tyres: ['https://picsum.photos/seed/swift-tyre1/800/600', 'https://picsum.photos/seed/swift-tyre2/800/600'],
    }
  },
  {
    id: '2',
    make: 'Hyundai',
    model: 'Creta',
    year: 2020,
    price: 1200000,
    kmsDriven: 40000,
    fuelType: 'Diesel',
    condition: 'Good',
    imageUrl: 'https://picsum.photos/seed/creta/600/400',
    imageHint: 'white suv',
    verified: true,
    transmission: 'Automatic',
    engine: '1.5L',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'SUV',
    registration: 'DL-03',
    insurance: 'Comprehensive',
    color: 'White',
    mileage: '18.5 kmpl',
    seatingCapacity: 5,
    vehicleType: '4-wheeler',
    detailImages: {
      Exterior: ['https://picsum.photos/seed/creta-ext1/800/600', 'https://picsum.photos/seed/creta-ext2/800/600'],
      Interior: ['https://picsum.photos/seed/creta-int1/800/600', 'https://picsum.photos/seed/creta-int2/800/600', 'https://picsum.photos/seed/creta-int3/800/600'],
      Engine: ['https://picsum.photos/seed/creta-eng1/800/600'],
      Tyres: ['https://picsum.photos/seed/creta-tyre1/800/600'],
    }
  },
  {
    id: '3',
    make: 'Honda',
    model: 'City',
    year: 2019,
    price: 900000,
    kmsDriven: 60000,
    fuelType: 'Petrol',
    condition: 'Good',
    imageUrl: 'https://picsum.photos/seed/city/600/400',
    imageHint: 'silver sedan',
    verified: false,
    transmission: 'Automatic',
    engine: '1.5L',
    ownership: '2nd Owner',
    serviceHistory: 'Not Available',
    bodyType: 'Sedan',
    registration: 'KA-01',
    insurance: 'Third Party',
    color: 'Silver',
    mileage: '17.4 kmpl',
    seatingCapacity: 5,
    vehicleType: '4-wheeler',
    detailImages: {
      Exterior: ['https://picsum.photos/seed/city-ext1/800/600', 'https://picsum.photos/seed/city-ext2/800/600'],
      Interior: ['https://picsum.photos/seed/city-int1/800/600', 'https://picsum.photos/seed/city-int2/800/600'],
      Engine: ['https://picsum.photos/seed/city-eng1/800/600'],
      Tyres: ['https://picsum.photos/seed/city-tyre1/800/600', 'https://picsum.photos/seed/city-tyre2/800/600'],
    }
  },
  {
    id: '4',
    make: 'Tata',
    model: 'Nexon EV',
    year: 2022,
    price: 1500000,
    kmsDriven: 15000,
    fuelType: 'Electric',
    condition: 'New',
    imageUrl: 'https://picsum.photos/seed/nexon/600/400',
    imageHint: 'blue suv',
    verified: true,
    transmission: 'Automatic',
    engine: 'N/A',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'SUV',
    registration: 'MH-04',
    insurance: 'Comprehensive',
    color: 'Blue',
    mileage: '312 km/charge',
    seatingCapacity: 5,
    vehicleType: '4-wheeler',
    detailImages: {
      Exterior: ['https://picsum.photos/seed/nexon-ext1/800/600', 'https://picsum.photos/seed/nexon-ext2/800/600'],
      Interior: ['https://picsum.photos/seed/nexon-int1/800/600', 'https://picsum.photos/seed/nexon-int2/800/600'],
      Engine: [],
      Tyres: ['https://picsum.photos/seed/nexon-tyre1/800/600'],
    }
  },
  {
    id: '5',
    make: 'Toyota',
    model: 'Innova Crysta',
    year: 2018,
    price: 1800000,
    kmsDriven: 80000,
    fuelType: 'Diesel',
    condition: 'Fair',
    imageUrl: 'https://picsum.photos/seed/innova/600/400',
    imageHint: 'grey mpv',
    verified: true,
    transmission: 'Manual',
    engine: '2.4L',
    ownership: '2nd Owner',
    serviceHistory: 'Available',
    bodyType: 'MPV',
    registration: 'TN-07',
    insurance: 'Expired',
    color: 'Grey',
    mileage: '12 kmpl',
    seatingCapacity: 7,
    vehicleType: '4-wheeler',
    detailImages: {
      Exterior: ['https://picsum.photos/seed/innova-ext1/800/600', 'https://picsum.photos/seed/innova-ext2/800/600'],
      Interior: ['https://picsum.photos/seed/innova-int1/800/600', 'https://picsum.photos/seed/innova-int2/800/600'],
      Engine: ['https://picsum.photos/seed/innova-eng1/800/600'],
      Tyres: ['https://picsum.photos/seed/innova-tyre1/800/600'],
    }
  },
  {
    id: '6',
    make: 'Kia',
    model: 'Seltos',
    year: 2021,
    price: 1350000,
    kmsDriven: 30000,
    fuelType: 'Petrol',
    condition: 'Like New',
    imageUrl: 'https://picsum.photos/seed/seltos/600/400',
    imageHint: 'black suv',
    verified: true,
    transmission: 'Automatic',
    engine: '1.5L',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'SUV',
    registration: 'PB-10',
    insurance: 'Comprehensive',
    color: 'Black',
    mileage: '16.8 kmpl',
    seatingCapacity: 5,
    vehicleType: '4-wheeler',
    detailImages: {
      Exterior: ['https://picsum.photos/seed/seltos-ext1/800/600', 'https://picsum.photos/seed/seltos-ext2/800/600'],
      Interior: ['https://picsum.photos/seed/seltos-int1/800/600'],
      Engine: ['https://picsum.photos/seed/seltos-eng1/800/600'],
      Tyres: ['https://picsum.photos/seed/seltos-tyre1/800/600', 'https://picsum.photos/seed/seltos-tyre2/800/600', 'https://picsum.photos/seed/seltos-tyre3/800/600'],
    }
  },
  {
    id: '7',
    make: 'Mahindra',
    model: 'Thar',
    year: 2022,
    price: 1600000,
    kmsDriven: 10000,
    fuelType: 'Diesel',
    condition: 'New',
    imageUrl: 'https://picsum.photos/seed/thar/600/400',
    imageHint: 'black jeep',
    verified: false,
    transmission: 'Manual',
    engine: '2.2L',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'Off-road',
    registration: 'RJ-14',
    insurance: 'Third Party',
    color: 'Black',
    mileage: '15.2 kmpl',
    seatingCapacity: 4,
    vehicleType: '4-wheeler',
    detailImages: {
      Exterior: ['https://picsum.photos/seed/thar-ext1/800/600', 'https://picsum.photos/seed/thar-ext2/800/600', 'https://picsum.photos/seed/thar-ext3/800/600'],
      Interior: ['https://picsum.photos/seed/thar-int1/800/600'],
      Engine: ['https://picsum.photos/seed/thar-eng1/800/600'],
      Tyres: ['https://picsum.photos/seed/thar-tyre1/800/600'],
    }
  },
  {
    id: '8',
    make: 'Volkswagen',
    model: 'Polo',
    year: 2017,
    price: 550000,
    kmsDriven: 70000,
    fuelType: 'Petrol',
    condition: 'Fair',
    imageUrl: 'https://picsum.photos/seed/polo/600/400',
    imageHint: 'blue hatchback',
    verified: true,
    transmission: 'Manual',
    engine: '1.0L',
    ownership: '2nd Owner',
    serviceHistory: 'Not Available',
    bodyType: 'Hatchback',
    registration: 'GA-08',
    insurance: 'Comprehensive',
    color: 'Blue',
    mileage: '17.75 kmpl',
    seatingCapacity: 5,
    vehicleType: '4-wheeler',
    detailImages: {
      Exterior: ['https://picsum.photos/seed/polo-ext1/800/600'],
      Interior: ['https://picsum.photos/seed/polo-int1/800/600', 'https://picsum.photos/seed/polo-int2/800/600'],
      Engine: ['https://picsum.photos/seed/polo-eng1/800/600'],
      Tyres: ['https://picsum.photos/seed/polo-tyre1/800/600'],
    }
  },
  {
    id: '9',
    make: 'Ford',
    model: 'EcoSport',
    year: 2019,
    price: 850000,
    kmsDriven: 55000,
    fuelType: 'Diesel',
    condition: 'Good',
    imageUrl: 'https://picsum.photos/seed/ecosport/600/400',
    imageHint: 'orange suv',
    verified: true,
    transmission: 'Manual',
    engine: '1.5L',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'SUV',
    registration: 'GJ-05',
    insurance: 'Comprehensive',
    color: 'Orange',
    mileage: '21.7 kmpl',
    seatingCapacity: 5,
    vehicleType: '4-wheeler',
    detailImages: {
      Exterior: ['https://picsum.photos/seed/ecosport-ext1/800/600', 'https://picsum.photos/seed/ecosport-ext2/800/600'],
      Interior: ['https://picsum.photos/seed/ecosport-int1/800/600'],
      Engine: ['https://picsum.photos/seed/ecosport-eng1/800/600'],
      Tyres: ['https://picsum.photos/seed/ecosport-tyre1/800/600'],
    }
  },
  {
    id: '10',
    make: 'Renault',
    model: 'Kwid',
    year: 2020,
    price: 400000,
    kmsDriven: 35000,
    fuelType: 'Petrol',
    condition: 'Good',
    imageUrl: 'https://picsum.photos/seed/kwid/600/400',
    imageHint: 'white hatchback',
    verified: true,
    transmission: 'Manual',
    engine: '1.0L',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'Hatchback',
    registration: 'UP-32',
    insurance: 'Third Party',
    color: 'White',
    mileage: '22.3 kmpl',
    seatingCapacity: 5,
    vehicleType: '4-wheeler',
    detailImages: {
      Exterior: ['https://picsum.photos/seed/kwid-ext1/800/600'],
      Interior: ['https://picsum.photos/seed/kwid-int1/800/600', 'https://picsum.photos/seed/kwid-int2/800/600'],
      Engine: ['https://picsum.photos/seed/kwid-eng1/800/600'],
      Tyres: ['https://picsum.photos/seed/kwid-tyre1/800/600'],
    }
  },
  {
    id: '11',
    make: 'Maruti Suzuki',
    model: 'Ertiga',
    year: 2021,
    price: 1050000,
    kmsDriven: 45000,
    fuelType: 'CNG',
    condition: 'Like New',
    imageUrl: 'https://picsum.photos/seed/ertiga/600/400',
    imageHint: 'brown mpv',
    verified: false,
    transmission: 'Manual',
    engine: '1.5L',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'MPV',
    registration: 'WB-02',
    insurance: 'Comprehensive',
    color: 'Brown',
    mileage: '26.08 km/kg',
    seatingCapacity: 7,
    vehicleType: '4-wheeler',
    detailImages: {
      Exterior: ['https://picsum.photos/seed/ertiga-ext1/800/600', 'https://picsum.photos/seed/ertiga-ext2/800/600'],
      Interior: ['https://picsum.photos/seed/ertiga-int1/800/600', 'https://picsum.photos/seed/ertiga-int2/800/600'],
      Engine: ['https://picsum.photos/seed/ertiga-eng1/800/600'],
      Tyres: ['https://picsum.photos/seed/ertiga-tyre1/800/600'],
    }
  },
  {
    id: '12',
    make: 'Hyundai',
    model: 'i20',
    year: 2022,
    price: 800000,
    kmsDriven: 12000,
    fuelType: 'Petrol',
    condition: 'New',
    imageUrl: 'https://picsum.photos/seed/i20/600/400',
    imageHint: 'red hatchback',
    verified: true,
    transmission: 'Automatic',
    engine: '1.2L',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'Hatchback',
    registration: 'CH-01',
    insurance: 'Comprehensive',
    color: 'Red',
    mileage: '20.28 kmpl',
    seatingCapacity: 5,
    vehicleType: '4-wheeler',
    detailImages: {
      Exterior: ['https://picsum.photos/seed/i20-ext1/800/600', 'https://picsum.photos/seed/i20-ext2/800/600'],
      Interior: ['https://picsum.photos/seed/i20-int1/800/600', 'https://picsum.photos/seed/i20-int2/800/600'],
      Engine: ['https://picsum.photos/seed/i20-eng1/800/600'],
      Tyres: ['https://picsum.photos/seed/i20-tyre1/800/600'],
    }
  },
   // 2-Wheelers
  {
    id: '13',
    make: 'Royal Enfield',
    model: 'Classic 350',
    year: 2021,
    price: 180000,
    kmsDriven: 12000,
    fuelType: 'Petrol',
    condition: 'Like New',
    imageUrl: 'https://picsum.photos/seed/classic350/600/400',
    imageHint: 'black motorcycle',
    verified: true,
    transmission: 'Manual',
    engine: '349cc',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'Cruiser',
    registration: 'MH-14',
    insurance: 'Comprehensive',
    color: 'Black',
    mileage: '35 kmpl',
    seatingCapacity: 2,
    vehicleType: '2-wheeler',
    detailImages: {
      Exterior: ['https://picsum.photos/seed/classic350-ext1/800/600'],
      Interior: [],
      Engine: ['https://picsum.photos/seed/classic350-eng1/800/600'],
      Tyres: ['https://picsum.photos/seed/classic350-tyre1/800/600'],
    }
  },
  {
    id: '14',
    make: 'TVS',
    model: 'Apache RTR 160',
    year: 2020,
    price: 95000,
    kmsDriven: 20000,
    fuelType: 'Petrol',
    condition: 'Good',
    imageUrl: 'https://picsum.photos/seed/apache160/600/400',
    imageHint: 'red motorcycle',
    verified: true,
    transmission: 'Manual',
    engine: '160cc',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'Sports',
    registration: 'DL-05',
    insurance: 'Third Party',
    color: 'Red',
    mileage: '45 kmpl',
    seatingCapacity: 2,
    vehicleType: '2-wheeler',
    detailImages: {
      Exterior: ['https://picsum.photos/seed/apache160-ext1/800/600'],
      Interior: [],
      Engine: ['https://picsum.photos/seed/apache160-eng1/800/600'],
      Tyres: ['https://picsum.photos/seed/apache160-tyre1/800/600'],
    }
  },
  {
    id: '15',
    make: 'Honda',
    model: 'Activa 6G',
    year: 2022,
    price: 75000,
    kmsDriven: 8000,
    fuelType: 'Petrol',
    condition: 'New',
    imageUrl: 'https://picsum.photos/seed/activa6g/600/400',
    imageHint: 'blue scooter',
    verified: true,
    transmission: 'Automatic',
    engine: '110cc',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'Scooter',
    registration: 'KA-03',
    insurance: 'Comprehensive',
    color: 'Blue',
    mileage: '50 kmpl',
    seatingCapacity: 2,
    vehicleType: '2-wheeler',
    detailImages: {
      Exterior: ['https://picsum.photos/seed/activa6g-ext1/800/600'],
      Interior: [],
      Engine: ['https://picsum.photos/seed/activa6g-eng1/800/600'],
      Tyres: ['https://picsum.photos/seed/activa6g-tyre1/800/600'],
    }
  },
  {
    id: '16',
    make: 'Bajaj',
    model: 'Pulsar 150',
    year: 2019,
    price: 85000,
    kmsDriven: 30000,
    fuelType: 'Petrol',
    condition: 'Good',
    imageUrl: 'https://picsum.photos/seed/pulsar150/600/400',
    imageHint: 'black motorcycle',
    verified: false,
    transmission: 'Manual',
    engine: '150cc',
    ownership: '2nd Owner',
    serviceHistory: 'Not Available',
    bodyType: 'Sports',
    registration: 'UP-14',
    insurance: 'Comprehensive',
    color: 'Black',
    mileage: '48 kmpl',
    seatingCapacity: 2,
    vehicleType: '2-wheeler',
    detailImages: {
      Exterior: ['https://picsum.photos/seed/pulsar150-ext1/800/600'],
      Interior: [],
      Engine: ['https://picsum.photos/seed/pulsar150-eng1/800/600'],
      Tyres: ['https://picsum.photos/seed/pulsar150-tyre1/800/600'],
    }
  },
];
