import type { Vehicle } from './types';

export const vehicles: Vehicle[] = [
  {
    id: '1',
    make: 'Maruti Suzuki',
    model: 'Swift',
    year: 2021,
    price: 650000,
    kmsDriven: 25000,
    fuelType: 'Petrol',
    condition: 'Like New',
    imageUrl: 'https://picsum.photos/seed/swift/600/400',
    imageHint: 'red hatchback',
    verified: true,
    transmission: 'Manual',
    engine: '1.2L',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'Hatchback',
    registration: 'MH-12',
    insurance: 'Comprehensive',
    color: 'Red',
    mileage: '23.2 kmpl',
    seatingCapacity: 5
  },
  {
    id: '2',
    make: 'Hyundai',
    model: 'Creta',
    year: 2020,
    price: 1200000,
    kmsDriven: 40000,
    fuelType: 'Diesel',
    condition: 'Good',
    imageUrl: 'https://picsum.photos/seed/creta/600/400',
    imageHint: 'white suv',
    verified: true,
    transmission: 'Automatic',
    engine: '1.5L',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'SUV',
    registration: 'DL-03',
    insurance: 'Comprehensive',
    color: 'White',
    mileage: '18.5 kmpl',
    seatingCapacity: 5
  },
  {
    id: '3',
    make: 'Honda',
    model: 'City',
    year: 2019,
    price: 900000,
    kmsDriven: 60000,
    fuelType: 'Petrol',
    condition: 'Good',
    imageUrl: 'https://picsum.photos/seed/city/600/400',
    imageHint: 'silver sedan',
    verified: false,
    transmission: 'Automatic',
    engine: '1.5L',
    ownership: '2nd Owner',
    serviceHistory: 'Not Available',
    bodyType: 'Sedan',
    registration: 'KA-01',
    insurance: 'Third Party',
    color: 'Silver',
    mileage: '17.4 kmpl',
    seatingCapacity: 5
  },
  {
    id: '4',
    make: 'Tata',
    model: 'Nexon EV',
    year: 2022,
    price: 1500000,
    kmsDriven: 15000,
    fuelType: 'Electric',
    condition: 'New',
    imageUrl: 'https://picsum.photos/seed/nexon/600/400',
    imageHint: 'blue suv',
    verified: true,
    transmission: 'Automatic',
    engine: 'N/A',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'SUV',
    registration: 'MH-04',
    insurance: 'Comprehensive',
    color: 'Blue',
    mileage: '312 km/charge',
    seatingCapacity: 5
  },
  {
    id: '5',
    make: 'Toyota',
    model: 'Innova Crysta',
    year: 2018,
    price: 1800000,
    kmsDriven: 80000,
    fuelType: 'Diesel',
    condition: 'Fair',
    imageUrl: 'https://picsum.photos/seed/innova/600/400',
    imageHint: 'grey mpv',
    verified: true,
    transmission: 'Manual',
    engine: '2.4L',
    ownership: '2nd Owner',
    serviceHistory: 'Available',
    bodyType: 'MPV',
    registration: 'TN-07',
    insurance: 'Expired',
    color: 'Grey',
    mileage: '12 kmpl',
    seatingCapacity: 7
  },
  {
    id: '6',
    make: 'Kia',
    model: 'Seltos',
    year: 2021,
    price: 1350000,
    kmsDriven: 30000,
    fuelType: 'Petrol',
    condition: 'Like New',
    imageUrl: 'https://picsum.photos/seed/seltos/600/400',
    imageHint: 'black suv',
    verified: true,
    transmission: 'Automatic',
    engine: '1.5L',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'SUV',
    registration: 'PB-10',
    insurance: 'Comprehensive',
    color: 'Black',
    mileage: '16.8 kmpl',
    seatingCapacity: 5
  },
  {
    id: '7',
    make: 'Mahindra',
    model: 'Thar',
    year: 2022,
    price: 1600000,
    kmsDriven: 10000,
    fuelType: 'Diesel',
    condition: 'New',
    imageUrl: 'https://picsum.photos/seed/thar/600/400',
    imageHint: 'black jeep',
    verified: false,
    transmission: 'Manual',
    engine: '2.2L',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'Off-road',
    registration: 'RJ-14',
    insurance: 'Third Party',
    color: 'Black',
    mileage: '15.2 kmpl',
    seatingCapacity: 4
  },
  {
    id: '8',
    make: 'Volkswagen',
    model: 'Polo',
    year: 2017,
    price: 550000,
    kmsDriven: 70000,
    fuelType: 'Petrol',
    condition: 'Fair',
    imageUrl: 'https://picsum.photos/seed/polo/600/400',
    imageHint: 'blue hatchback',
    verified: true,
    transmission: 'Manual',
    engine: '1.0L',
    ownership: '2nd Owner',
    serviceHistory: 'Not Available',
    bodyType: 'Hatchback',
    registration: 'GA-08',
    insurance: 'Comprehensive',
    color: 'Blue',
    mileage: '17.75 kmpl',
    seatingCapacity: 5
  },
  {
    id: '9',
    make: 'Ford',
    model: 'EcoSport',
    year: 2019,
    price: 850000,
    kmsDriven: 55000,
    fuelType: 'Diesel',
    condition: 'Good',
    imageUrl: 'https://picsum.photos/seed/ecosport/600/400',
    imageHint: 'orange suv',
    verified: true,
    transmission: 'Manual',
    engine: '1.5L',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'SUV',
    registration: 'GJ-05',
    insurance: 'Comprehensive',
    color: 'Orange',
    mileage: '21.7 kmpl',
    seatingCapacity: 5
  },
  {
    id: '10',
    make: 'Renault',
    model: 'Kwid',
    year: 2020,
    price: 400000,
    kmsDriven: 35000,
    fuelType: 'Petrol',
    condition: 'Good',
    imageUrl: 'https://picsum.photos/seed/kwid/600/400',
    imageHint: 'white hatchback',
    verified: true,
    transmission: 'Manual',
    engine: '1.0L',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'Hatchback',
    registration: 'UP-32',
    insurance: 'Third Party',
    color: 'White',
    mileage: '22.3 kmpl',
    seatingCapacity: 5
  },
  {
    id: '11',
    make: 'Maruti Suzuki',
    model: 'Ertiga',
    year: 2021,
    price: 1050000,
    kmsDriven: 45000,
    fuelType: 'CNG',
    condition: 'Like New',
    imageUrl: 'https://picsum.photos/seed/ertiga/600/400',
    imageHint: 'brown mpv',
    verified: false,
    transmission: 'Manual',
    engine: '1.5L',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'MPV',
    registration: 'WB-02',
    insurance: 'Comprehensive',
    color: 'Brown',
    mileage: '26.08 km/kg',
    seatingCapacity: 7
  },
  {
    id: '12',
    make: 'Hyundai',
    model: 'i20',
    year: 2022,
    price: 800000,
    kmsDriven: 12000,
    fuelType: 'Petrol',
    condition: 'New',
    imageUrl: 'https://picsum.photos/seed/i20/600/400',
    imageHint: 'red hatchback',
    verified: true,
    transmission: 'Automatic',
    engine: '1.2L',
    ownership: '1st Owner',
    serviceHistory: 'Available',
    bodyType: 'Hatchback',
    registration: 'CH-01',
    insurance: 'Comprehensive',
    color: 'Red',
    mileage: '20.28 kmpl',
    seatingCapacity: 5
  },
];
